/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.elsmancs.Enzinium;

import org.junit.Test;
import static org.junit.Assert.*;

public class AddressTest {

   Address prueba = new Address();

   @Test
    public void generateKeyPairTest() {
       prueba.generateKeyPair();
       System.out.println(prueba.toString());
   }

   @Test
   public void transferEZITest() {
      prueba.generateKeyPair();
      prueba.transferEZI(30d);
      double delta = 0.001;
      assertEquals(45, prueba.getBalance(),delta);
      System.out.println(prueba.toString());
   }
}
